static_page:
  per_page: 12
  search_book : books
  search_author: author
  search_category: category
borrowing_book_controller:
  per_page: 10
  search_book : s_books
  search_author: s_author
  search_category: s_category
